server:
  port: 8082
  session:

  servlet:
    session:
      cookie:
        name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client1:
            client-id: R2dpxQ3vPrtfgF723
            client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB93
            client-name: Auth Server
            scope: read
            provider: custom-provider
            redirect-uri: http://localhost:8082/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8084/auth/oauth/token
            authorization-uri: http://localhost:8084/auth/oauth/authorize
            user-info-uri: http://localhost:8084/auth/user/me
            user-name-attribute: name
